PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX icecream: <http://www.icecream.com/ontologies/icecream.owl#>

SELECT ?sundae
WHERE { ?sundae rdf:type icecream:Sundae .
                  ?sundae icecream:hasNuts ?nuts .
                  ?sundae icecream:hasTopping ?topping .
                   ?topping rdf:type icecream:FruitTopping .
                   FILTER(?nuts=false)}